services:
  login:
    image: auth-gateway-login:local
    environment:
      COOLIFY_RESOURCE_UUID: rcwwcgsw88ccocc8owkgk80w
      COOLIFY_CONTAINER_NAME: login-rcwwcgsw88ccocc8owkgk80w
      COOLIFY_FQDN: auth.sb.soltrix.dev
      COOLIFY_URL: https://auth.sb.soltrix.dev
      SERVICE_NAME_LOGIN: login
    expose:
    - '80'
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO- http://127.0.0.1/ >/dev/null || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
    labels:
      traefik.http.middlewares.login-root-redirect.redirectregex.regex: ^https?://auth\.sb\.soltrix\.dev/?$$$$
      traefik.http.middlewares.login-root-redirect.redirectregex.replacement: https://sb.soltrix.dev/
      traefik.http.middlewares.login-root-redirect.redirectregex.permanent: 'false'
      coolify.managed: 'true'
      coolify.version: 4.0.0-beta.444
      coolify.serviceId: '21'
      coolify.type: service
      coolify.name: login-rcwwcgsw88ccocc8owkgk80w
      coolify.resourceName: auth-login
      coolify.projectName: test
      coolify.serviceName: login
      coolify.environmentName: production
      coolify.pullRequestId: '0'
      coolify.service.subId: '49'
      coolify.service.subType: application
      coolify.service.subName: login
      traefik.enable: 'true'
      traefik.http.middlewares.gzip.compress: 'true'
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      traefik.http.routers.http-0-rcwwcgsw88ccocc8owkgk80w-login.entryPoints: http
      traefik.http.routers.http-0-rcwwcgsw88ccocc8owkgk80w-login.middlewares: redirect-to-https
      traefik.http.routers.http-0-rcwwcgsw88ccocc8owkgk80w-login.rule: Host(`auth.sb.soltrix.dev`) && PathPrefix(`/`)
      traefik.http.routers.https-0-rcwwcgsw88ccocc8owkgk80w-login.entryPoints: https
      traefik.http.routers.https-0-rcwwcgsw88ccocc8owkgk80w-login.middlewares: gzip,login-root-redirect
      traefik.http.routers.https-0-rcwwcgsw88ccocc8owkgk80w-login.rule: Host(`auth.sb.soltrix.dev`) && PathPrefix(`/`)
      traefik.http.routers.https-0-rcwwcgsw88ccocc8owkgk80w-login.tls.certresolver: letsencrypt
      traefik.http.routers.https-0-rcwwcgsw88ccocc8owkgk80w-login.tls: 'true'
      caddy_0.encode: zstd gzip
      caddy_0.handle_path.0_reverse_proxy: '{{upstreams}}'
      caddy_0.handle_path: /*
      caddy_0.header: -Server
      caddy_0.try_files: '{path} /index.html /index.php'
      caddy_0: https://auth.sb.soltrix.dev
      caddy_ingress_network: rcwwcgsw88ccocc8owkgk80w
      traefik.http.services.https-0-rcwwcgsw88ccocc8owkgk80w-login.loadbalancer.server.port: '80'
      traefik.http.routers.https-0-rcwwcgsw88ccocc8owkgk80w-login.service: https-0-rcwwcgsw88ccocc8owkgk80w-login
      traefik.http.routers.http-0-rcwwcgsw88ccocc8owkgk80w-login.service: https-0-rcwwcgsw88ccocc8owkgk80w-login
    container_name: login-rcwwcgsw88ccocc8owkgk80w
    restart: unless-stopped
    networks:
      rcwwcgsw88ccocc8owkgk80w: null
    env_file:
    - .env
networks:
  rcwwcgsw88ccocc8owkgk80w:
    name: rcwwcgsw88ccocc8owkgk80w
    external: true
