services:
  authentik-server:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2025.10.3}
    restart: unless-stopped
    command: server
    environment:
      SERVICE_URL_AUTHENTIKSERVER_9000: https://login.soltrix.dev:9000
      AUTHENTIK_POSTGRESQL__HOST: ${POSTGRES_HOST:-postgresql}
      AUTHENTIK_POSTGRESQL__USER: ${SERVICE_USER_POSTGRESQL}
      AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${SERVICE_PASSWORD_POSTGRESQL}
      AUTHENTIK_SECRET_KEY: ${SERVICE_PASSWORD_64_AUTHENTIKSERVER}
      AUTHENTIK_ERROR_REPORTING__ENABLED: ${AUTHENTIK_ERROR_REPORTING__ENABLED:-true}
      AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL__HOST}
      AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_EMAIL__PORT}
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL__PASSWORD}
      AUTHENTIK_EMAIL__USE_TLS: ${AUTHENTIK_EMAIL__USE_TLS}
      AUTHENTIK_EMAIL__USE_SSL: ${AUTHENTIK_EMAIL__USE_SSL}
      AUTHENTIK_EMAIL__TIMEOUT: ${AUTHENTIK_EMAIL__TIMEOUT}
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
      COOLIFY_RESOURCE_UUID: asc44o0ss8kgoo44gso04ggo
      COOLIFY_CONTAINER_NAME: authentik-server-asc44o0ss8kgoo44gso04ggo
      COOLIFY_FQDN: login.soltrix.dev
      COOLIFY_URL: https://login.soltrix.dev
      SERVICE_NAME_AUTHENTIK_SERVER: authentik-server
      SERVICE_NAME_AUTHENTIK_WORKER: authentik-worker
      SERVICE_NAME_POSTGRESQL: postgresql
    volumes:
    - /data/coolify/services/asc44o0ss8kgoo44gso04ggo/media:/media
    - /data/coolify/services/asc44o0ss8kgoo44gso04ggo/custom-templates:/templates
    depends_on:
      postgresql:
        condition: service_healthy
    labels:
      traefik.http.services.https-0-asc44o0ss8kgoo44gso04ggo-authentik-server.loadbalancer.server.port: '9000'
      traefik.http.routers.https-0-asc44o0ss8kgoo44gso04ggo-authentik-server.service: https-0-asc44o0ss8kgoo44gso04ggo-authentik-server
      traefik.http.routers.http-0-asc44o0ss8kgoo44gso04ggo-authentik-server.service: https-0-asc44o0ss8kgoo44gso04ggo-authentik-server
      coolify.managed: 'true'
      coolify.version: 4.0.0-beta.444
      coolify.serviceId: '18'
      coolify.type: service
      coolify.name: authentik-server-asc44o0ss8kgoo44gso04ggo
      coolify.resourceName: authentik-asc44o0ss8kgoo44gso04ggo
      coolify.projectName: test
      coolify.serviceName: authentik-server
      coolify.environmentName: production
      coolify.pullRequestId: '0'
      coolify.service.subId: '45'
      coolify.service.subType: application
      coolify.service.subName: authentik-server
      traefik.enable: 'true'
      traefik.http.middlewares.gzip.compress: 'true'
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      traefik.http.routers.http-0-asc44o0ss8kgoo44gso04ggo-authentik-server.entryPoints: http
      traefik.http.routers.http-0-asc44o0ss8kgoo44gso04ggo-authentik-server.middlewares: redirect-to-https
      traefik.http.routers.http-0-asc44o0ss8kgoo44gso04ggo-authentik-server.rule: Host(`auth.sb.soltrix.dev`) && PathPrefix(`/`)
      traefik.http.routers.https-0-asc44o0ss8kgoo44gso04ggo-authentik-server.entryPoints: https
      traefik.http.routers.https-0-asc44o0ss8kgoo44gso04ggo-authentik-server.middlewares: gzip,login-root-redirect
      traefik.http.routers.https-0-asc44o0ss8kgoo44gso04ggo-authentik-server.rule: Host(`auth.sb.soltrix.dev`) && PathPrefix(`/`)
      traefik.http.routers.https-0-asc44o0ss8kgoo44gso04ggo-authentik-server.tls.certresolver: letsencrypt
      traefik.http.routers.https-0-asc44o0ss8kgoo44gso04ggo-authentik-server.tls: 'true'
      caddy_0.encode: zstd gzip
      caddy_0.handle_path.0_reverse_proxy: '{{upstreams}}'
      caddy_0.handle_path: /*
      caddy_0.header: -Server
      caddy_0.try_files: '{path} /index.html /index.php'
      caddy_0: https://auth.sb.soltrix.dev
      caddy_ingress_network: asc44o0ss8kgoo44gso04ggo
      traefik.http.routers.outpost-studio.rule: Host(`sb.soltrix.dev`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.outpost-studio.entryPoints: https
      traefik.http.routers.outpost-studio.tls: 'true'
      traefik.http.routers.outpost-studio.tls.certresolver: letsencrypt
      traefik.http.routers.outpost-studio.service: https-0-asc44o0ss8kgoo44gso04ggo-authentik-server
      traefik.http.middlewares.login-root-redirect.redirectregex.regex: ^https?://auth\.sb\.soltrix\.dev/?$$
      traefik.http.middlewares.login-root-redirect.redirectregex.replacement: https://sb.soltrix.dev/
      traefik.http.middlewares.login-root-redirect.redirectregex.permanent: 'false'
    container_name: authentik-server-asc44o0ss8kgoo44gso04ggo
    networks:
      asc44o0ss8kgoo44gso04ggo: null
    env_file:
    - .env
  authentik-worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2025.10.3}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_POSTGRESQL__HOST: ${POSTGRES_HOST:-postgresql}
      AUTHENTIK_POSTGRESQL__USER: ${SERVICE_USER_POSTGRESQL}
      AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${SERVICE_PASSWORD_POSTGRESQL}
      AUTHENTIK_SECRET_KEY: ${SERVICE_PASSWORD_64_AUTHENTIKSERVER}
      AUTHENTIK_ERROR_REPORTING__ENABLED: ${AUTHENTIK_ERROR_REPORTING__ENABLED}
      AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL__HOST}
      AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_EMAIL__PORT}
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL__PASSWORD}
      AUTHENTIK_EMAIL__USE_TLS: ${AUTHENTIK_EMAIL__USE_TLS}
      AUTHENTIK_EMAIL__USE_SSL: ${AUTHENTIK_EMAIL__USE_SSL}
      AUTHENTIK_EMAIL__TIMEOUT: ${AUTHENTIK_EMAIL__TIMEOUT}
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
      COOLIFY_RESOURCE_UUID: asc44o0ss8kgoo44gso04ggo
      COOLIFY_CONTAINER_NAME: authentik-worker-asc44o0ss8kgoo44gso04ggo
      SERVICE_NAME_AUTHENTIK_SERVER: authentik-server
      SERVICE_NAME_AUTHENTIK_WORKER: authentik-worker
      SERVICE_NAME_POSTGRESQL: postgresql
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /data/coolify/services/asc44o0ss8kgoo44gso04ggo/media:/media
    - /data/coolify/services/asc44o0ss8kgoo44gso04ggo/certs:/certs
    - /data/coolify/services/asc44o0ss8kgoo44gso04ggo/custom-templates:/templates
    depends_on:
      postgresql:
        condition: service_healthy
    container_name: authentik-worker-asc44o0ss8kgoo44gso04ggo
    labels:
    - coolify.managed=true
    - coolify.version=4.0.0-beta.444
    - coolify.serviceId=18
    - coolify.type=service
    - coolify.name=authentik-worker-asc44o0ss8kgoo44gso04ggo
    - coolify.resourceName=authentik-asc44o0ss8kgoo44gso04ggo
    - coolify.projectName=test
    - coolify.serviceName=authentik-worker
    - coolify.environmentName=production
    - coolify.pullRequestId=0
    - coolify.service.subId=46
    - coolify.service.subType=application
    - coolify.service.subName=authentik-worker
    networks:
      asc44o0ss8kgoo44gso04ggo: null
    env_file:
    - .env
  postgresql:
    image: postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      timeout: 10s
      retries: 15
    volumes:
    - asc44o0ss8kgoo44gso04ggo_authentik-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRESQL}
      POSTGRES_USER: ${SERVICE_USER_POSTGRESQL}
      POSTGRES_DB: authentik
      COOLIFY_RESOURCE_UUID: asc44o0ss8kgoo44gso04ggo
      COOLIFY_CONTAINER_NAME: postgresql-asc44o0ss8kgoo44gso04ggo
      SERVICE_NAME_AUTHENTIK_SERVER: authentik-server
      SERVICE_NAME_AUTHENTIK_WORKER: authentik-worker
      SERVICE_NAME_POSTGRESQL: postgresql
    container_name: postgresql-asc44o0ss8kgoo44gso04ggo
    labels:
    - coolify.managed=true
    - coolify.version=4.0.0-beta.444
    - coolify.serviceId=18
    - coolify.type=service
    - coolify.name=postgresql-asc44o0ss8kgoo44gso04ggo
    - coolify.resourceName=authentik-asc44o0ss8kgoo44gso04ggo
    - coolify.projectName=test
    - coolify.serviceName=postgresql
    - coolify.environmentName=production
    - coolify.pullRequestId=0
    - coolify.service.subId=11
    - coolify.service.subType=database
    - coolify.service.subName=postgresql
    networks:
      asc44o0ss8kgoo44gso04ggo: null
    env_file:
    - .env
volumes:
  asc44o0ss8kgoo44gso04ggo_authentik-db:
    name: asc44o0ss8kgoo44gso04ggo_authentik-db
networks:
  asc44o0ss8kgoo44gso04ggo:
    name: asc44o0ss8kgoo44gso04ggo
    external: true
