services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_SERVER_URL: https://s3.soltrix.dev
      MINIO_BROWSER_REDIRECT_URL: https://minio.soltrix.dev
      MINIO_ROOT_USER: IC58vp4BwfnLkdf0
      MINIO_ROOT_PASSWORD: UQpb5lTT7SPFnnsqHbk1cD98hr7S9m4b
      COOLIFY_RESOURCE_UUID: rk4cgsggk0kocccsgksgcs48
      COOLIFY_CONTAINER_NAME: minio-rk4cgsggk0kocccsgksgcs48
      SERVICE_NAME_MINIO: minio
    volumes:
    - rk4cgsggk0kocccsgksgcs48_minio-data:/data
    healthcheck:
      test:
      - CMD-SHELL
      - mc ready local || curl -f http://127.0.0.1:9000/minio/health/live
      interval: 10s
      timeout: 10s
      retries: 5
    container_name: minio-rk4cgsggk0kocccsgksgcs48
    restart: unless-stopped
    labels:
      coolify.managed: 'true'
      coolify.version: 4.0.0-beta.444
      coolify.serviceId: '19'
      coolify.type: service
      coolify.name: minio-rk4cgsggk0kocccsgksgcs48
      coolify.resourceName: minio
      coolify.projectName: test
      coolify.serviceName: minio
      coolify.environmentName: production
      coolify.pullRequestId: '0'
      coolify.service.subId: '47'
      coolify.service.subType: application
      coolify.service.subName: minio
      traefik.enable: 'true'
      traefik.http.routers.https-1-rk4cgsggk0kocccsgksgcs48-minio.rule: Host(`s3.soltrix.dev`)
      traefik.http.routers.https-1-rk4cgsggk0kocccsgksgcs48-minio.entryPoints: https
      traefik.http.routers.https-1-rk4cgsggk0kocccsgksgcs48-minio.tls: 'true'
      traefik.http.routers.https-1-rk4cgsggk0kocccsgksgcs48-minio.tls.certresolver: letsencrypt
      traefik.http.routers.https-1-rk4cgsggk0kocccsgksgcs48-minio.service: https-1-rk4cgsggk0kocccsgksgcs48-minio
      traefik.http.services.https-1-rk4cgsggk0kocccsgksgcs48-minio.loadbalancer.server.port: '9000'
      traefik.http.routers.http-1-rk4cgsggk0kocccsgksgcs48-minio.rule: Host(`s3.soltrix.dev`)
      traefik.http.routers.http-1-rk4cgsggk0kocccsgksgcs48-minio.entryPoints: http
      traefik.http.routers.http-1-rk4cgsggk0kocccsgksgcs48-minio.middlewares: redirect-to-https
      traefik.http.routers.http-1-rk4cgsggk0kocccsgksgcs48-minio.service: https-1-rk4cgsggk0kocccsgksgcs48-minio
      traefik.http.routers.https-2-rk4cgsggk0kocccsgksgcs48-minio.rule: Host(`minio.soltrix.dev`)
      traefik.http.routers.https-2-rk4cgsggk0kocccsgksgcs48-minio.entryPoints: https
      traefik.http.routers.https-2-rk4cgsggk0kocccsgksgcs48-minio.tls: 'true'
      traefik.http.routers.https-2-rk4cgsggk0kocccsgksgcs48-minio.tls.certresolver: letsencrypt
      traefik.http.routers.https-2-rk4cgsggk0kocccsgksgcs48-minio.service: https-2-rk4cgsggk0kocccsgksgcs48-minio
      traefik.http.services.https-2-rk4cgsggk0kocccsgksgcs48-minio.loadbalancer.server.port: '9001'
      traefik.http.routers.http-2-rk4cgsggk0kocccsgksgcs48-minio.rule: Host(`minio.soltrix.dev`)
      traefik.http.routers.http-2-rk4cgsggk0kocccsgksgcs48-minio.entryPoints: http
      traefik.http.routers.http-2-rk4cgsggk0kocccsgksgcs48-minio.middlewares: redirect-to-https
      traefik.http.routers.http-2-rk4cgsggk0kocccsgksgcs48-minio.service: https-2-rk4cgsggk0kocccsgksgcs48-minio
    networks:
      rk4cgsggk0kocccsgksgcs48: null
    env_file:
    - .env
volumes:
  rk4cgsggk0kocccsgksgcs48_minio-data:
    name: rk4cgsggk0kocccsgksgcs48_minio-data
networks:
  rk4cgsggk0kocccsgksgcs48:
    name: rk4cgsggk0kocccsgksgcs48
    external: true
