services:
  supabase-kong:
    image: kong/kong:3.9.1
    entrypoint: /home/kong/kong-entrypoint.sh
    depends_on:
      supabase-analytics:
        condition: service_healthy
    healthcheck:
      test:
      - CMD
      - kong
      - health
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      SERVICE_URL_SUPABASEKONG_8000: https://${API_HOST}
      KONG_PORT_MAPS: 443:8000
      JWT_SECRET: ${SUPABASE_JWT_SECRET}
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_DNS_NOT_FOUND_TTL: '1'
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth,request-termination,ip-restriction,post-function
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      KONG_PROXY_ACCESS_LOG: /dev/stdout combined
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY:-}
      SUPABASE_SECRET_KEY: ${SUPABASE_SECRET_KEY:-}
      ANON_KEY_ASYMMETRIC: ${ANON_KEY_ASYMMETRIC:-}
      SERVICE_ROLE_KEY_ASYMMETRIC: ${SERVICE_ROLE_KEY_ASYMMETRIC:-}
      DASHBOARD_USERNAME: ${STUDIO_USER}
      DASHBOARD_PASSWORD: ${STUDIO_PASSWORD}
      KONG_STORAGE_CONNECT_TIMEOUT: ${KONG_STORAGE_CONNECT_TIMEOUT:-60}
      KONG_STORAGE_WRITE_TIMEOUT: ${KONG_STORAGE_WRITE_TIMEOUT:-3600}
      KONG_STORAGE_READ_TIMEOUT: ${KONG_STORAGE_READ_TIMEOUT:-3600}
      KONG_STORAGE_REQUEST_BUFFERING: ${KONG_STORAGE_REQUEST_BUFFERING:-false}
      KONG_STORAGE_RESPONSE_BUFFERING: ${KONG_STORAGE_RESPONSE_BUFFERING:-false}
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    volumes:
    - ./volumes/api/kong-entrypoint.sh:/home/kong/kong-entrypoint.sh
    - ./volumes/api/kong.yml:/home/kong/temp.yml
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  supabase-studio:
    image: supabase/studio:2026.03.16-sha-5528817
    healthcheck:
      test:
      - CMD
      - node
      - -e
      - fetch('http://127.0.0.1:3000/api/platform/profile').then((r) => {if (r.status !== 200) throw new Error(r.status)})
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      supabase-analytics:
        condition: service_healthy
    environment:
      HOSTNAME: 0.0.0.0
      STUDIO_PG_META_URL: http://supabase-meta:8080
      POSTGRES_PASSWORD: ${SUPABASE_INTERNAL_PG_PASS}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS:-public,storage,graphql_public}
      PGRST_DB_MAX_ROWS: ${PGRST_DB_MAX_ROWS:-1000}
      PGRST_DB_EXTRA_SEARCH_PATH: ${PGRST_DB_EXTRA_SEARCH_PATH:-public}
      DEFAULT_ORGANIZATION_NAME: ${STUDIO_DEFAULT_ORGANIZATION:-Default Organization}
      DEFAULT_PROJECT_NAME: ${STUDIO_DEFAULT_PROJECT:-Default Project}
      SUPABASE_URL: http://supabase-kong:8000
      SUPABASE_PUBLIC_URL: https://${API_HOST}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      AUTH_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      PG_META_CRYPTO_KEY: ${PG_META_CRYPTO_KEY}
      LOGFLARE_API_KEY: ${LOGFLARE_API_KEY}
      LOGFLARE_PUBLIC_ACCESS_TOKEN: ${LOGFLARE_API_KEY}
      LOGFLARE_PRIVATE_ACCESS_TOKEN: ${LOGFLARE_PRIVATE_ACCESS_TOKEN}
      LOGFLARE_URL: http://supabase-analytics:4000
      NEXT_PUBLIC_SUPABASE_URL: https://${API_HOST}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      NEXT_PUBLIC_ENABLE_LOGS: 'true'
      NEXT_ANALYTICS_BACKEND_PROVIDER: postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SNIPPETS_MANAGEMENT_FOLDER: /app/snippets
      EDGE_FUNCTIONS_MANAGEMENT_FOLDER: /app/edge-functions
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    volumes:
    - snippets-data:/app/snippets
    - ./volumes/functions:/app/edge-functions
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  supabase-analytics:
    image: supabase/logflare:1.31.2
    healthcheck:
      test:
      - CMD
      - curl
      - http://127.0.0.1:4000/health
      timeout: 5s
      interval: 5s
      retries: 10
    environment:
      LOGFLARE_NODE_HOST: 127.0.0.1
      DB_USERNAME: supabase_admin
      DB_DATABASE: _supabase
      DB_HOSTNAME: postgres
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_PASSWORD: ${SUPABASE_INTERNAL_PG_PASS}
      DB_SCHEMA: _analytics
      LOGFLARE_PUBLIC_ACCESS_TOKEN: ${LOGFLARE_API_KEY}
      LOGFLARE_PRIVATE_ACCESS_TOKEN: ${LOGFLARE_PRIVATE_ACCESS_TOKEN}
      LOGFLARE_SINGLE_TENANT: 'true'
      LOGFLARE_SUPABASE_MODE: 'true'
      POSTGRES_BACKEND_URL: postgresql://supabase_admin:${SUPABASE_INTERNAL_PG_PASS}@postgres:${POSTGRES_PORT:-5432}/_supabase
      POSTGRES_BACKEND_SCHEMA: _analytics
      LOGFLARE_FEATURE_FLAG_OVERRIDE: multibackend=true
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  supabase-vector:
    image: timberio/vector:0.53.0-alpine
    healthcheck:
      test:
      - CMD
      - wget
      - --no-verbose
      - --tries=1
      - --spider
      - http://supabase-vector:9001/health
      timeout: 5s
      interval: 5s
      retries: 3
    volumes:
    - ./volumes/logs/vector.yml:/etc/vector/vector.yml
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LOGFLARE_PUBLIC_ACCESS_TOKEN: ${LOGFLARE_API_KEY}
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    command:
    - --config
    - /etc/vector/vector.yml
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  supabase-rest:
    image: postgrest/postgrest:v14.6
    depends_on:
      supabase-analytics:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://authenticator:${SUPABASE_INTERNAL_PG_PASS}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS:-public,storage,graphql_public}
      PGRST_DB_MAX_ROWS: ${PGRST_DB_MAX_ROWS:-1000}
      PGRST_DB_EXTRA_SEARCH_PATH: ${PGRST_DB_EXTRA_SEARCH_PATH:-public}
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: 'false'
      PGRST_APP_SETTINGS_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      PGRST_APP_SETTINGS_JWT_EXP: ${JWT_EXPIRY:-3600}
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    command: postgrest
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  supabase-auth:
    image: supabase/gotrue:v2.186.0
    depends_on:
      supabase-analytics:
        condition: service_healthy
    healthcheck:
      test:
      - CMD
      - wget
      - --no-verbose
      - --tries=1
      - --spider
      - http://127.0.0.1:9999/health
      timeout: 5s
      interval: 5s
      retries: 3
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: '9999'
      API_EXTERNAL_URL: ${API_EXTERNAL_URL:-http://supabase-kong:8000}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${SUPABASE_INTERNAL_PG_PASS}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      GOTRUE_SITE_URL: https://${SB_HOST}/auth/
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS}
      GOTRUE_DISABLE_SIGNUP: 'true'
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY:-3600}
      GOTRUE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: 'false'
      GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED: ${ENABLE_ANONYMOUS_USERS:-false}
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM:-false}
      GOTRUE_SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL}
      GOTRUE_SMTP_HOST: ${SMTP_HOST}
      GOTRUE_SMTP_PORT: ${SMTP_PORT:-587}
      GOTRUE_SMTP_USER: ${SMTP_USER}
      GOTRUE_SMTP_PASS: ${SMTP_PASS}
      GOTRUE_SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
      GOTRUE_MAILER_URLPATHS_INVITE: ${MAILER_URLPATHS_INVITE:-/auth/v1/verify}
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: ${MAILER_URLPATHS_CONFIRMATION:-/auth/v1/verify}
      GOTRUE_MAILER_URLPATHS_RECOVERY: ${MAILER_URLPATHS_RECOVERY:-/auth/v1/verify}
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: ${MAILER_URLPATHS_EMAIL_CHANGE:-/auth/v1/verify}
      GOTRUE_MAILER_TEMPLATES_INVITE: ${MAILER_TEMPLATES_INVITE}
      GOTRUE_MAILER_TEMPLATES_CONFIRMATION: ${MAILER_TEMPLATES_CONFIRMATION}
      GOTRUE_MAILER_TEMPLATES_RECOVERY: ${MAILER_TEMPLATES_RECOVERY}
      GOTRUE_MAILER_TEMPLATES_MAGIC_LINK: ${MAILER_TEMPLATES_MAGIC_LINK}
      GOTRUE_MAILER_TEMPLATES_EMAIL_CHANGE: ${MAILER_TEMPLATES_EMAIL_CHANGE}
      GOTRUE_MAILER_SUBJECTS_CONFIRMATION: ${MAILER_SUBJECTS_CONFIRMATION}
      GOTRUE_MAILER_SUBJECTS_RECOVERY: ${MAILER_SUBJECTS_RECOVERY}
      GOTRUE_MAILER_SUBJECTS_MAGIC_LINK: ${MAILER_SUBJECTS_MAGIC_LINK}
      GOTRUE_MAILER_SUBJECTS_EMAIL_CHANGE: ${MAILER_SUBJECTS_EMAIL_CHANGE}
      GOTRUE_MAILER_SUBJECTS_INVITE: ${MAILER_SUBJECTS_INVITE}
      GOTRUE_EXTERNAL_PHONE_ENABLED: ${ENABLE_PHONE_SIGNUP:-true}
      GOTRUE_SMS_AUTOCONFIRM: ${ENABLE_PHONE_AUTOCONFIRM:-true}
      GOTRUE_EXTERNAL_GOOGLE_ENABLED: 'true'
      GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOTRUE_EXTERNAL_GOOGLE_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      ADDITIONAL_REDIRECT_URLS: ${ADDITIONAL_REDIRECT_URLS}
      SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
      MAILER_TEMPLATES_INVITE: ${MAILER_TEMPLATES_INVITE}
      MAILER_TEMPLATES_CONFIRMATION: ${MAILER_TEMPLATES_CONFIRMATION}
      MAILER_TEMPLATES_RECOVERY: ${MAILER_TEMPLATES_RECOVERY}
      MAILER_TEMPLATES_MAGIC_LINK: ${MAILER_TEMPLATES_MAGIC_LINK}
      MAILER_TEMPLATES_EMAIL_CHANGE: ${MAILER_TEMPLATES_EMAIL_CHANGE}
      MAILER_SUBJECTS_CONFIRMATION: ${MAILER_SUBJECTS_CONFIRMATION}
      MAILER_SUBJECTS_RECOVERY: ${MAILER_SUBJECTS_RECOVERY}
      MAILER_SUBJECTS_MAGIC_LINK: ${MAILER_SUBJECTS_MAGIC_LINK}
      MAILER_SUBJECTS_EMAIL_CHANGE: ${MAILER_SUBJECTS_EMAIL_CHANGE}
      MAILER_SUBJECTS_INVITE: ${MAILER_SUBJECTS_INVITE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  realtime-dev:
    image: supabase/realtime:v2.76.5
    depends_on:
      supabase-analytics:
        condition: service_healthy
    healthcheck:
      test:
      - CMD
      - curl
      - -sSfL
      - --head
      - -o
      - /dev/null
      - -H
      - 'Authorization: Bearer ${SUPABASE_ANON_KEY}'
      - http://127.0.0.1:4000/api/tenants/realtime-dev/health
      timeout: 5s
      interval: 5s
      retries: 3
      start_period: 10s
    environment:
      PORT: '4000'
      DB_HOST: postgres
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_USER: supabase_admin
      DB_PASSWORD: ${SUPABASE_INTERNAL_PG_PASS}
      DB_NAME: ${POSTGRES_DB:-postgres}
      DB_AFTER_CONNECT_QUERY: SET search_path TO _realtime
      DB_ENC_KEY: supabaserealtime
      API_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      SECRET_KEY_BASE: ${SECRET_PASSWORD_REALTIME}
      METRICS_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      ERL_AFLAGS: -proto_dist inet_tcp
      DNS_NODES: ''''''
      RLIMIT_NOFILE: '10000'
      APP_NAME: realtime
      SEED_SELF_HOST: 'true'
      LOG_LEVEL: error
      RUN_JANITOR: 'true'
      JANITOR_INTERVAL: '60000'
      DISABLE_HEALTHCHECK_LOGGING: 'true'
      SECRET_PASSWORD_REALTIME: ${SECRET_PASSWORD_REALTIME}
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    command: 'sh -c "/app/bin/migrate && /app/bin/realtime eval ''Realtime.Release.seeds(Realtime.Repo)'' && /app/bin/server"

      '
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  supabase-storage:
    image: supabase/storage-api:v1.44.2
    depends_on:
      supabase-rest:
        condition: service_started
      imgproxy:
        condition: service_started
    healthcheck:
      test:
      - CMD
      - wget
      - --no-verbose
      - --tries=1
      - --spider
      - http://127.0.0.1:5000/status
      timeout: 5s
      interval: 5s
      retries: 3
    environment:
      SERVER_PORT: '5000'
      SERVER_REGION: local
      MULTI_TENANT: 'false'
      AUTH_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      DATABASE_URL: postgres://supabase_storage_admin:${SUPABASE_INTERNAL_PG_PASS}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      DB_INSTALL_ROLES: 'false'
      STORAGE_BACKEND: s3
      STORAGE_S3_BUCKET: stub
      STORAGE_S3_ENDPOINT: http://minio:9000
      STORAGE_S3_FORCE_PATH_STYLE: 'true'
      STORAGE_S3_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      UPLOAD_FILE_SIZE_LIMIT: '524288000'
      UPLOAD_FILE_SIZE_LIMIT_STANDARD: '524288000'
      UPLOAD_SIGNED_URL_EXPIRATION_TIME: '120'
      TUS_URL_PATH: /upload/resumable
      TUS_MAX_SIZE: '3600000'
      ENABLE_IMAGE_TRANSFORMATION: 'true'
      IMGPROXY_URL: http://imgproxy:8080
      IMGPROXY_REQUEST_TIMEOUT: '15'
      DATABASE_SEARCH_PATH: storage
      NODE_ENV: production
      REQUEST_ALLOW_X_FORWARDED_PATH: 'true'
      ANON_KEY: ${SUPABASE_ANON_KEY}
      SERVICE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      POSTGREST_URL: http://supabase-rest:3000
      PGRST_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      STORAGE_PUBLIC_URL: https://${API_HOST}
      TENANT_ID: ${STORAGE_TENANT_ID:-storage-single-tenant}
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    volumes:
    - storage-data:/var/lib/storage
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  imgproxy:
    image: darthsim/imgproxy:v3.30.1
    healthcheck:
      test:
      - CMD
      - imgproxy
      - health
      timeout: 5s
      interval: 5s
      retries: 3
    environment:
      IMGPROXY_BIND: :8080
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /
      IMGPROXY_USE_ETAG: 'true'
      IMGPROXY_AUTO_WEBP: ${IMGPROXY_AUTO_WEBP:-true}
      IMGPROXY_MAX_SRC_RESOLUTION: '16.8'
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    volumes:
    - storage-data:/var/lib/storage
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  supabase-meta:
    image: supabase/postgres-meta:v0.95.2
    depends_on:
      supabase-analytics:
        condition: service_healthy
    environment:
      PG_META_PORT: '8080'
      PG_META_DB_HOST: postgres
      PG_META_DB_PORT: ${POSTGRES_PORT:-5432}
      PG_META_DB_NAME: ${POSTGRES_DB:-postgres}
      PG_META_DB_USER: supabase_admin
      PG_META_DB_PASSWORD: ${SUPABASE_INTERNAL_PG_PASS}
      CRYPTO_KEY: ${PG_META_CRYPTO_KEY}
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  supabase-edge-functions:
    image: supabase/edge-runtime:v1.71.2
    depends_on:
      supabase-analytics:
        condition: service_healthy
    healthcheck:
      test:
      - CMD
      - echo
      - Edge Functions is healthy
      timeout: 5s
      interval: 5s
      retries: 3
    environment:
      JWT_SECRET: ${SUPABASE_JWT_SECRET}
      SUPABASE_URL: http://supabase-kong:8000
      SUPABASE_PUBLIC_URL: https://${API_HOST}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_DB_URL: postgresql://postgres:${SUPABASE_INTERNAL_PG_PASS}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      VERIFY_JWT: ${FUNCTIONS_VERIFY_JWT:-false}
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    volumes:
    - ./volumes/functions:/home/deno/functions
    - deno-cache:/root/.cache/deno
    - ./volumes/functions/main/index.ts:/home/deno/functions/main/index.ts
    - ./volumes/functions/hello/index.ts:/home/deno/functions/hello/index.ts
    command:
    - start
    - --main-service
    - /home/deno/functions/main
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  supabase-supavisor:
    image: supabase/supavisor:2.7.4
    healthcheck:
      test:
      - CMD
      - curl
      - -sSfL
      - -o
      - /dev/null
      - http://127.0.0.1:4000/api/health
      timeout: 5s
      interval: 5s
      retries: 10
      start_period: 30s
    depends_on:
      supabase-analytics:
        condition: service_healthy
    environment:
      POOLER_TENANT_ID: ${POOLER_TENANT_ID:-dev_tenant}
      POOLER_POOL_MODE: transaction
      POOLER_DEFAULT_POOL_SIZE: ${POOLER_DEFAULT_POOL_SIZE:-20}
      POOLER_MAX_CLIENT_CONN: ${POOLER_MAX_CLIENT_CONN:-100}
      PORT: '4000'
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${SUPABASE_INTERNAL_PG_PASS}
      DATABASE_URL: ecto://supabase_admin:${SUPABASE_INTERNAL_PG_PASS}@postgres:${POSTGRES_PORT:-5432}/_supabase
      CLUSTER_POSTGRES: 'true'
      SECRET_KEY_BASE: ${SUPAVISOR_SECRET_KEY_BASE}
      VAULT_ENC_KEY: ${SUPAVISOR_VAULT_ENC_KEY}
      API_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      METRICS_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      REGION: local
      ERL_AFLAGS: -proto_dist inet_tcp
      DB_POOL_SIZE: ${POOLER_DB_POOL_SIZE:-5}
      GLOBAL_DOWNSTREAM_CERT_PATH: /etc/ssl/server.crt
      GLOBAL_DOWNSTREAM_KEY_PATH: /etc/ssl/server.key
      SERVICE_NAME_SUPABASE_KONG: supabase-kong
      SERVICE_NAME_SUPABASE_STUDIO: supabase-studio
      SERVICE_NAME_SUPABASE_ANALYTICS: supabase-analytics
      SERVICE_NAME_SUPABASE_VECTOR: supabase-vector
      SERVICE_NAME_SUPABASE_REST: supabase-rest
      SERVICE_NAME_SUPABASE_AUTH: supabase-auth
      SERVICE_NAME_REALTIME_DEV: realtime-dev
      SERVICE_NAME_SUPABASE_MINIO: supabase-minio
      SERVICE_NAME_MINIO_CREATEBUCKET: minio-createbucket
      SERVICE_NAME_SUPABASE_STORAGE: supabase-storage
      SERVICE_NAME_IMGPROXY: imgproxy
      SERVICE_NAME_SUPABASE_META: supabase-meta
      SERVICE_NAME_SUPABASE_EDGE_FUNCTIONS: supabase-edge-functions
      SERVICE_NAME_SUPABASE_SUPAVISOR: supabase-supavisor
    command:
    - /bin/sh
    - -c
    - "if [ ! -f /etc/ssl/server.crt ]; then\n  openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \\\n    -keyout /etc/ssl/server.key -out /etc/ssl/server.crt \\\n    -subj \"/CN=supabase-pooler\"\nfi\n/app/bin/migrate && /app/bin/supavisor eval \"$$(cat /etc/pooler/pooler.exs)\" && /app/bin/server\n"
    volumes:
    - ./volumes/pooler/pooler.exs:/etc/pooler/pooler.exs
    ports:
    - 6543:6543
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  postgres:
    image: supabase/postgres:15.8.1.060
    environment:
      POSTGRES_USER: supabase_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - pgsodium-config:/etc/postgresql-custom
    command:
    - postgres
    - -c
    - shared_preload_libraries=pgsodium,pg_stat_statements,pgaudit,pg_cron,pg_net
    - -c
    - pgsodium.getkey_script=/etc/postgresql-custom/pgsodium_getkey.sh
    - -c
    - wal_level=logical
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U supabase_admin
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: https://${S3_HOST}
      MINIO_BROWSER_REDIRECT_URL: https://${MINIO_CONSOLE_HOST}
    volumes:
    - minio-data:/data
    healthcheck:
      test:
      - CMD-SHELL
      - mc ready local || curl -f http://127.0.0.1:9000/minio/health/live
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  validator:
    image: auth-gateway-validator:local
    environment:
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      LOGIN_URL: https://${SB_HOST}/auth
      COOKIE_NAME: sb-access-token
      PORT: '8080'
      OWNER_EMAIL: ${OWNER_EMAIL}
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO- http://127.0.0.1:8080/healthz | grep -q ok
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  login:
    image: auth-gateway-login:local
    environment:
      COOKIE_DOMAIN: .${PARENT_DOMAIN}
      LOGOUT_REDIRECT: https://${SB_HOST}/
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO- http://127.0.0.1/auth/ >/dev/null || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    env_file:
    - path: ../../.env
      required: false
  caddy:
    image: caddy:2-alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile:ro
    - caddy-data:/data
    - caddy-config:/config
    environment:
      SB_HOST: ${SB_HOST}
      API_HOST: ${API_HOST}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
      S3_HOST: ${S3_HOST}
      MINIO_CONSOLE_HOST: ${MINIO_CONSOLE_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
    - validator
    - login
    - supabase-kong
    - supabase-studio
    - minio
    restart: unless-stopped
volumes:
  deno-cache: {}
  postgres-data: {}
  pgsodium-config: {}
  minio-data: {}
  caddy-data: {}
  caddy-config: {}
  storage-data: {}
  snippets-data: {}
